apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend                                 # 2
spec:                                                # 3
  containers:
    # - image: rinormaloku/sentiment-analysis-frontend # 4
    - image: kevinedwards/sentiment-analysis-frontend:v1.0.0 # 4
      name: sa-frontend                              # 5
      ports:
        - containerPort: 80                          # 6
