version: '3.7'

services:
  sa-logic:
    image: sentiment-analysis-logic
    build:
      context: ./sa-logic
    container_name: sa-logic
    ports:
      - ${SA_LOGIC_PORT}:5000
    networks:
      - default

  sa-web:
    image: sentiment-analysis-web
    build:
      context: ./sa-webapp
    container_name: sa-web
    environment:
      - SA_LOGIC_API_URL=${SA_LOGIC_API_URL}:${SA_LOGIC_PORT}
    ports:
      - ${SA_WEBAPP_PORT}:8080
    networks:
      - default
    depends_on:
      - sa-logic

  sa-frontend:
    image: sentiment-analysis-frontend
    build:
      context: ./sa-frontend
    container_name: sa-frontend
    stdin_open: true
    environment:
      - NODE_ENV=development
      - WEB_APP_API_URL=http://sa-web:8000
    volumes:
      - ./sa-frontend/src:/app
      - /app/node_modules
    ports:
      - ${SA_FRONTEND_PORT}:3000
    depends_on:
      - sa-web
    networks:
      - default

networks:
  default:
    name: sentiment-analysis-network