---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  labels:
    volume: sqlite
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/db"