apiVersion: v1
kind: Pod
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  containers:
    - image: kevinedwards/sentiment-analysis-frontend:1.0.0
      name: sa-frontend
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 150m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
